apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wrb3dcwhs-nodejs
  janus-idp.io/tekton: wrb3dcwhs-nodejs
  backstage.io/kubernetes-id: wrb3dcwhs-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wrb3dcwhs-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
